### ISSUE TITLE
Copilots with "requested" invite can see projects in the list

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#419] opened 2019-12-12 03:08 UTC
### Actual behavior
When we request an invitation for a copilot to the Topcoder Team they can see the project listed.

### Expected behavior
When we request an invitation for a copilot to the Topcoder Team they shouldn't see such a project listed until they have the invite request accepted.

### How to reproduce:
1. Invite `pshah_copilot` using `pshah_manager` to any project as `copilot` (using Topcoder Team dialog).

    ![image](https://user-images.githubusercontent.com/146016/70679007-d0320080-1cce-11ea-8118-71ba370872ec.png)

2. As `pshah_manager` doesn't have "Copilot Management" permission, `pshah_copilot` wouldn't be added to the project but his invite would be `requested` and waiting for any Copilot Manager to "accept" it. Don't accept it.
3. Now log in with `pshah_copilot` and you would see the project where copilot has "requested" invite listed on the project listing page:

    ![image](https://user-images.githubusercontent.com/146016/70678987-b85a7c80-1cce-11ea-8347-361b8ab3ef6c.png)
4. At the same time if Copilot would try to open such a project, they would get error 404, as expected, because copilot is not a member.

This is an existent issue in V4 which has been also migrated to V5.

@vikasrohit, could you please confirm that it's a valid issue and the actual behavior is not desired.

**Comment by vikasrohit** [comment] 2019-12-12 09:48
Agreed. we need to fix it before the release. It is a bug.

**Comment by vikasrohit** [comment] 2019-12-19 12:08
It is fixed, @maxceem ?

**Comment by maxceem** [comment] 2019-12-23 04:44
Fixed in DB request, but not in ES. I will take care of it asap.

**Comment by maxceem** [comment] 2019-12-23 07:33
Run F2F for this https://www.topcoder.com/challenges/30111699

**Comment by maxceem** [comment] 2019-12-24 04:26
Got the solution from F2F. @vikasrohit would like me to create a HOTFIX or just merge it to `dev`?

**Comment by vikasrohit** [comment] 2019-12-24 05:25
Hotfix is good as we have sufficient time in this week to monitor. Hope the changes are not big, I mean the probability of any regression is very less.

**Comment by maxceem** [comment] 2019-12-24 07:38
@vikasrohit there are hotfixes:
PROD https://github.com/topcoder-platform/tc-project-service/pull/433
DEV https://github.com/topcoder-platform/tc-project-service/pull/434

**Comment by vikasrohit** [comment] 2019-12-24 08:51
@maxceem merged the dev version first, please let me know it works for you in dev (once the build is complete).

**Comment by maxceem** [comment] 2019-12-24 09:38
@vikasrohit Works well for me on DEV.

**Comment by vikasrohit** [comment] 2019-12-24 11:27
Deployed to the production.

**Comment by lakshmiathreya** [comment] 2019-12-24 12:12
@vikasrohit is 2.0.0 the correct milestone? Also, am unable to edit this Issue ... would like to verify and close it ...

**Comment by lakshmiathreya** [comment] 2019-12-24 12:12
cc @nithyaasworld

**Comment by vikasrohit** [comment] 2019-12-24 12:17
> @vikasrohit is 2.0.0 the correct milestone? Also, am unable to edit this Issue ... would like to verify and close it ...

I am not sure but I usually include the hotfixes in the upcoming milestone because until recently github didn't allow to include an issue in closed milestone. However, now as it allows us to include the issues in closed milestones, I am thinking of including such hotfixes in last closed milestone. fyi, release for the hotfix is https://github.com/topcoder-platform/tc-project-service/releases/tag/2.0.0.1

**Comment by lakshmiathreya** [comment] 2019-12-24 12:20
Milestone is 2.0.0.1 for this hotfix in that case. We referred to the v5
release as 2.5 earlier. It should have been 2.0.0?

**Comment by vikasrohit** [comment] 2019-12-24 12:25
Creating milestone for a hotfix seems overkill to me, that is why we don't create milestones for them. However, as it is a new release I appended `.1` to the previous release `2.0.0`. I think we can keep hotfixes in previously closed milestone and tag a separate release.

**Comment by maxceem** [comment] 2020-01-06 06:12
Fix for this issue has been pushed to PROD as a HOTFIX and might be closed.

**Closed** 2020-01-06 06:15 UTC
Labels: hotfix
