### ISSUE TITLE
Don't return email address in the PUT call for invite

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#464] opened 2020-02-06 07:29 UTC
Seems like right now we are returning the email of the invited user always, no matter if calling user is admin or not.

**Comment by maxceem** [comment] 2020-02-06 08:42
### How to reproduce

Invite some user by `handle` using non-admin who should not see emails. For example, using `pshah_manager` invite `pshah_customer` to some project. In the tooltip the `pshah_manger` would see the email of invited `pshah_customer`:

![image](https://user-images.githubusercontent.com/146016/73919856-52b9f380-48ff-11ea-81ca-938a7d9ffef8.png)

### Expected behavior

Non-admin users should not see emails of invited users if user is invited by `handle`. If user is invited by `email` any user still can see the email (for now).

**Comment by maxceem** [comment] 2020-02-06 10:00
Note, that we return email not only when `PUT`, but also when `GET` one or several invites, so all the cases should be fixed.

**Comment by maxceem** [comment] 2020-02-06 10:06
### Hot to verify

We should verify several things:
1. Admin users **can see email** in the invite tooltips when invited existent Topcoder user.

   ![image](https://user-images.githubusercontent.com/146016/73926514-b695e980-490a-11ea-949a-d77e5d896f4c.png)

2. Non-admin users **should not** see the email in the invite tooltips when invited existent Topcoder user.

3. Any user **can see email** in the tooltip if we invite non-registered user (no topcoder account), because we don't have anything except of email.

4. Test for regressions.
    We should be able to remove the invitation:
    - when an existent user is invited by the handle
    - when an existent user is invited by email
    - when a non-registered user is invited by email

**Comment by vikasrohit** [comment] 2020-02-07 07:14
@maxceem I deployed the hotfix to the production as I didn't want to delay the hotfix till next week. However, after the deploy, as you suspected, I am, as customer, not able to remove the invited member.

**Comment by vikasrohit** [comment] 2020-02-07 07:28
One more observation @maxceem, right now system is allowing inviting people even after project is cancelled. Do you remember if we had that as feature.

**Comment by maxceem** [comment] 2020-02-07 08:36
> @maxceem I deployed the hotfix to the production as I didn't want to delay the hotfix till next week. However, after the deploy, as you suspected, I am, as customer, not able to remove the invited member.

@vikasrohit there is a hotfix for Connect App to fix the issue with removing the invitations https://github.com/appirio-tech/connect-app/pull/3700

**Comment by maxceem** [comment] 2020-02-07 08:39
> One more observation @maxceem, right now system is allowing inviting people even after project is cancelled. Do you remember if we had that as feature.

I don't remember making any special cases for `canceled` projects differently. So I guess most of the operations for `canceled` projects would work the same as for other statuses.

**Comment by vikasrohit** [comment] 2020-02-07 11:02
Okay.

**Comment by maxceem** [comment] 2020-04-03 12:52
@vikasrohit We've finished invites refactoring and took care of email in the latest `2.2` release, so I think this can be closed.

**Closed** 2020-04-05 09:05 UTC
Labels: P1, hotfix
