### ISSUE TITLE
Different data in milestones is returned with `/v4/timelines/ID/milestones` and `/v4/timelines?filter=...`

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#159] opened 2018-08-07 06:52 UTC
There was another related issue which is fixed https://github.com/topcoder-platform/tc-project-service/issues/116

For now when we get data of the same timeline using different endpoints `/v4/timelines/ID/milestones` and `/v4/timelines?filter=...` we get different data in milestones. `/v4/timelines?filter=...` returns not updated data.

### Here are example requests to quick check:
- https://api.topcoder-dev.com/v4/timelines?filter=reference%3Dproduct%26referenceId%3D1176
- https://api.topcoder-dev.com/v4/timelines/302

Both of them return timeline with `id=302` and there is a milestone with `id=1075`. In first case its status is `reviewed` which is an old value. And in the second case its status is `active` which is the new value.

### How to reproduce from the begining:
1. Create a new **Website** project https://connect.topcoder-dev.com/new-project/
2. Got to Project Plan tab, edit the first phase and chage status to **In Progress** to make the first milestone active.
3. Mark first active milestone as completed.
4. You will end up with the next picture, where first milestone is completed and the second milestone is active:

    ![image](https://user-images.githubusercontent.com/146016/43758938-46b808e2-9a50-11e8-91fb-7870730479d9.png)

5. Now you can open browser console Network tab and reload the page to see the requests.
    It will look something like this:

    ![image](https://user-images.githubusercontent.com/146016/43759075-bbd1f6b0-9a50-11e8-8f06-a24251fa7671.png)

    You can check that they returned differenet status for the second milestone.

**Comment by vikasrohit** [comment] 2018-08-07 10:57
@maxceem I am unable to reproduce the issue. I followed the steps and it seems both endpoints returns the same status for the milestones and they should because they both are reading from the same place that is ES index. The get time line by id endpoint is trying to sort the milestones but as the request does not specify the `sort` param, it is sorting it randomly. So, you might see different milestone at the same index. Could that be the reason you are seeing different status?

**Comment by maxceem** [comment] 2018-08-07 11:12
@vikasrohit I've noticed the difference in sorting, but despite it, I still can reproduce the issue. Maybe I'm missing something else?

I use the user `pat_monahan`. And make the next two requests in Postman:

1. https://api.topcoder-dev.com/v4/timelines?filter=reference%3Dproduct%26referenceId%3D1176
    It returns the next object with timeline, I left only `community-milestone` in the milestones property to keep it short:

   ```js
    {
                "createdAt": "2018-08-07T06:41:29.000Z",
                "updatedAt": "2018-08-07T06:41:29.000Z",
                "id": 302,
                "name": "Welcome to the Website Development phase",
                "description": "This is the first stage in our project. We’re going to show you the detailed plan in your timeline, with all the milestones.",
                "startDate": "2018-08-07T00:00:00.000Z",
                "endDate": null,
                "reference": "product",
                "referenceId": 1176,
                "createdBy": 40152933,
                "updatedBy": 40152933,
                "milestones": [
                  {
                        "updatedBy": 40152933,
                        "hidden": false,
                        "endDate": "2018-08-21T00:00:00.000Z",
                        "completedText": "Your backend development has been completed. You've reached the end of this milestone.",
                        "activeText": "Development is underway. We will update this milestone once the progress bar reaches 100%.",
                        "timelineId": 302,
                        "description": "Please review and answer all the questions on the specification document before we can proceed",
                        "type": "community-work",
                        "duration": 5,
                        "createdAt": "2018-08-07T06:41:29.000Z",
                        "createdBy": 40152933,
                        "name": "community-work",
                        "plannedText": "We will be analyzing and building the features from your [oproject_type] specification. This is the rough development that will be refined over the next [number] milestones.",
                        "details": {},
                        "id": 1075,
                        "blockedText": "community-work MileStone Is Blocked",
                        "startDate": "2018-08-17T00:00:00.000Z",
                        "status": "reviewed",
                        "order": 2,
                        "updatedAt": "2018-08-07T06:41:29.000Z"
                    }
           ]
   }
   ```
   The full response here https://codeshare.io/29rKNV

2. And for https://api.topcoder-dev.com/v4/timelines/302
    Here is the timeline object it returns, again I kept the same `communit-work` milestone on the list to keep it short:
    ```js
      {
            "id": 302,
            "name": "Welcome to the Website Development phase",
            "description": "This is the first stage in our project. We’re going to show you the detailed plan in your timeline, with all the milestones.",
            "startDate": "2018-08-07T00:00:00.000Z",
            "endDate": "2018-08-23T00:00:00.000Z",
            "reference": "product",
            "referenceId": 1176,
            "createdAt": "2018-08-07T06:41:29.000Z",
            "updatedAt": "2018-08-07T06:43:20.000Z",
            "createdBy": 40152933,
            "updatedBy": 40152933,
            "milestones": [
                {
                    "id": 1075,
                    "name": "community-work",
                    "description": "Please review and answer all the questions on the specification document before we can proceed",
                    "duration": 5,
                    "startDate": "2018-08-08T00:00:00.000Z",
                    "endDate": "2018-08-12T00:00:00.000Z",
                    "completionDate": null,
                    "status": "active",
                    "type": "community-work",
                    "details": {},
                    "order": 2,
                    "plannedText": "We will be analyzing and building the features from your [oproject_type] specification. This is the rough development that will be refined over the next [number] milestones.",
                    "activeText": "Development is underway. We will update this milestone once the progress bar reaches 100%.",
                    "completedText": "Your backend development has been completed. You've reached the end of this milestone.",
                    "blockedText": "community-work MileStone Is Blocked",
                    "hidden": false,
                    "createdAt": "2018-08-07T06:41:29.000Z",
                    "updatedAt": "2018-08-07T06:43:20.000Z",
                    "createdBy": 40152933,
                    "updatedBy": 40152933,
                    "timelineId": 302
                }
            ]
     }
    ```

     The full response here https://codeshare.io/adoNyD

You can see that in responses that there are the same timelines, and the same milestones, but statuses of milestones are different.

**Comment by vikasrohit** [comment] 2018-08-07 11:49
Thanks @maxceem for the detailed debug logs. I got it now. Yes, there is a bug, working on it.

**Comment by vikasrohit** [comment] 2018-08-10 13:15
Should be fixed now. I tested it on dev and it seems to work fine now. Only catch is that if it takes some time to index the data in ES and before that front end makes a call to fetch the timelines by `reference` and `referenceId` it still might return old data. To overcome that we should put a fallback call to the timeline by id endpoint only when we are marking a milestone complete if we don't see next milestone's status being 'active'.

fyi @maxceem @RishiRajSahu

**Closed by vikasrohit** 2018-08-10 13:15 UTC
